version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3

commands:
  print_pipeline_id:
    steps:
      - run:
          name: Print workflow ID
          command:
            echo ${CIRCLE_WORKFLOW_ID:0:7}


jobs:
  setup-environment:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - print_pipeline_id
      - checkout
      - run:
          name: make setup
          command: |
            make setup
      - run:
          name: make install
          command: |
            make install
      - run:
          name: make lint
          command: |
            make lint
  build-docker:
    docker:
      - image: docker:latest
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install dependencies
          command: |
            apk update && apk add bash
      - run:
          name: build docker
          command: |
            sh ./run_docker.sh
            sh ./upload_docker.sh

workflows:
  captone:
    jobs:
      - setup-environment
      - build-docker:
          requires: [setup-environment]