version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3

commands:
  print_pipeline_id:
    steps:
      - run:
          name: Print workflow ID
          command:
            echo ${CIRCLE_WORKFLOW_ID:0:7}


jobs:
  setup-environment:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - print_pipeline_id
      - checkout
      - run:
          name: make setup (via Makefile)
          command: |
            make setup
      - run:
          name: make install (via Makefile)
          command: |
            make install
      - run:
          name: make lint (via Makefile)
          command: |
            make lint

workflows:
  captone:
    jobs:
      - setup-environment